### ISSUE TITLE
task navigation 

### ISSUE THREAD

**Issue by Haghend** [LejusVDP/AMOGUS#10]
la task du milieu, celle du calibrage je n'arrive pas à la faire.
Mon rond bleu est parfaitement positionné avec le rouge mais la task ne se complète pas 
![Screenshot_1](https://user-images.githubusercontent.com/95180043/143776616-c07e9172-1434-41ac-b9e2-35d0a6274a9c.png)

**Comment by LejusV** [comment]
Testé plusieurs fois et tout semble fonctionner correctement, j'ai rajouté le `/advancement revoke @s only amogus:tasks/navigation/steering` manquant lors du clic sur le villageois de la task.

EDIT : ça arrivait en fait quand on cliquait en courant du coup on continuait le petit élan de notre course malgré le slow et du coup ça décalait notre position et notre curseur ne pouvait plus atteindre la cible. Réglé en ajoutant un délai d'une demi-seconde avant l'apparaition de la cible !
